### ISSUE TITLE
1tp crashes on name resolution failure

### ISSUE THREAD

**Issue by thomasdelaet** [MicroMinion/1tp#17]
error: { Error: getaddrinfo EAI_AGAIN
    at Object.exports._errnoException (util.js:1007:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'dht-bootstrap-1.microminion.io' } module=1tp:transports
/home/thomas/repositories/1tp/src/utils.js:31
    throw new Error(error)
    ^

Error: Error: getaddrinfo EAI_AGAIN
    at UdpTransport.object._error (/home/thomas/repositories/1tp/src/utils.js:31:11)
    at Socket.<anonymous> (/home/thomas/repositories/1tp/src/transports/udp.js:175:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at doSend (dgram.js:373:10)
    at afterDns (dgram.js:361:5)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:65:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:79:17)

**Comment by thomasdelaet** [comment]
should be fixed when pull request is merged
